dist: trusty

language: node_js
node_js:
  - "10"

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - cd src/

jobs:
    include:
        - stage: Backend Unit Test
          script:
              - docker build -f db-helper/Dockerfile -t pymongo:0.1 db-helper/
              - docker-compose -f docker/docker-compose-test.yaml up -d
              - docker exec -it -w /app docker_backend_1 bash -c 'npm install'
              - docker exec -it -w /app docker_backend_1 bash -c 'npm run test'
        - stage: Frontend Unit Test
          script:
              - docker build -f db-helper/Dockerfile -t pymongo:0.1 db-helper/
              - echo 'REACT_APP_BACKEND_URL=http://localhost:3000/todo' > src/frontend/todo-frontend/.env.development.local
              - docker-compose -f docker/docker-compose-test.yaml up -d
              - docker exec -it -w /app docker_frontend_1 bash -c 'npm install'
              - docker exec -it -w /app docker_frontend_1 bash -c 'CI=true npm run test'

              