version: '3.1'

services:

  pymongo:
    image: pymongo:0.1
    restart: on-failure
    volumes:
      - ../db-helper/db-helper.py:/app/db-helper.py
      - ../db-helper/data.json:/app/data.json
    working_dir: /app
    command: ./db-helper.py

  backend:
    image: node:10-jessie
    restart: always
    working_dir: /app
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000
    volumes:
      - ../backend/todo-server:/app
    
  frontend:
    image: node:10-jessie
    restart: always
    working_dir: /app
    command: ["npm", "run-script", "start"]
    ports:
      - 4000:4000
    volumes:
      - ../frontend/todo-frontend:/app
    environment:
      HOST: 0.0.0.0
      PORT: 4000

  mongo:
    image: mongo:3.4.23-xenial
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: thisispassword
